name: Build Downstream Projects

on:
  push:
    # Uncomment before merging
    # branches:
    #   - main

permissions:
  issues: write 

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'jacobtomlinson/sphinx-llm'
    strategy:
      matrix:
        python-version: ["3.12"]
        downstream-project: [
          {
            "name":"nolar/kopf",
            "path":"kopf", 
            "install_command": "uv pip install --group docs -e .", 
            "build_command": "sphinx-build docs/ docs/_build/ -b html"
          }
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Checkout Downstream Project
        uses: actions/checkout@v6
        with:
          repository: ${{ matrix.downstream-project.name }}
          path: ${{ matrix.downstream-project.path }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6.3.1
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}

      - name: Install Downstream Project
        run: |
          cd ${{ matrix.downstream-project.path }}
          ${{ matrix.downstream-project.install_command }}

      - name: Install sphinx-llm
        run: |
          uv pip install -e .

      - name: Build Downstream Project
        id: build-downstream-project
        run: |
          cd ${{ matrix.downstream-project.path }}
          ${{ matrix.downstream-project.build_command }}

      - name: Open issue if build fails
        if: failure() && steps.build-downstream-project.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Downstream build failed for ${process.env.GITHUB_SHA.substring(0, 8)}: ${{ matrix.downstream-project.name }}`,
              body: `Downstream testing failed, see ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            });
